name: gutendex
description: Menampilkan buku yang ada di Gutendex.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  dartz: ^0.10.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  url_launcher: ^6.1.6
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  language_picker: ^0.4.1
  cached_network_image: ^3.2.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/book.png"
  min_sdk_android: 21

  windows:
    generate: true
    image_path: "assets/images/book.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
